[package]
name = "gpu"
version = "0.1.0"
edition = "2024"

[features]
default = ["device-fault"]
device-fault = []

[dependencies]
bytemuck = { workspace = true }
bitflags = "2.10.0"
smart-default = "0.7.1"
vulkanalia = { workspace = true }
vulkanalia-vma = "0.8.0"
anyhow = { workspace = true }
log = { workspace = true }
glam = { workspace = true }
